# Каждый docker-file должен начинаться с № версии
version: '3'

# Сервисы (или контейнеры), которые будут подключаться
services:
  # nginx [engine x] — это HTTP-сервер и обратный прокси-сервер,
  # почтовый прокси-сервер, а также TCP/UDP прокси-сервер общего назначения
  nginx: # название сервиса (может быть любым)
    container_name: nginx
    build: ./requirements/nginx # откуда берем docker-file
    env_file: # говорим compose, что у нас будет специальный
      - .env  # файл для переменной окружения
    hostname: localhost
    volumes:
      - wp:/var/www/html/wordpress # где создаем том
    networks:
      - project # название сети, к которой будет подключаться модуль
                # (описывается в самом конце)
    depends_on:
      - wordpress # устанавливаем зависимость
    ports:
    # устанавливаем порт с которым будет соединяться наш контейнер
    # по сабжекту - это порт 443
    # [порт компьютера]:[порт контейнера]
      - "443:443"
    restart: always # инструкции при остановке образа

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    hostname: localhost
    volumes:
      - db:/var/lib/mysql
    networks:
      - project

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file:
      - .env
    hostname: localhost
    volumes:
      - wp:/var/www/html/wordpress
    networks:
      - project
    depends_on:
      - mariadb

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    ports:
      - "6379:6379"
    networks:
      - project
    restart: always

# Тома (volumes) - используются для запоминания информации даже
# после перезапуска контейнеров
# Содержимое сохраняется по адресу: /var/lib/docker/volumes/
volumes:
  db:
    # name: db
    driver: local
    driver_opts: # описывает необязательные занчения драйвера для данной сети
      type: none # тип сервиса контейнера
      # type: the mount type volume, bind, tmpfs or npipe
      o: bind # устанавливает специфические опции для драйвера
      # аналог --opt
      device: /home/${USER}/Desktop/data/db # куда сохраняются данные для каждого сериса
  wp:
    # name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/Desktop/data/wp

# настройка внутренней сети
networks:
  project: # название сети
    driver: bridge # тип сети
